// File generated by FlutterFire CLI.
// This is a placeholder file. Run ./configure_firebase.sh or ./setup.sh to generate the real configuration.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGk3uIctgw0wx-b2Mi1lDZMFYADcHrrSM',
    appId: '1:241414034513:web:7fb63f9b93f8f996fd9470',
    messagingSenderId: '241414034513',
    projectId: 'testg2-8640',
    authDomain: 'testg2-8640.firebaseapp.com',
    storageBucket: 'testg2-8640.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAse95eBJ9bcaz9WmtBt_1clGbJfDTaxtg',
    appId: '1:241414034513:android:9d85d4b6c2c03e8cfd9470',
    messagingSenderId: '241414034513',
    projectId: 'testg2-8640',
    storageBucket: 'testg2-8640.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIahd0GVTAGsJH-kAdBxjjd4Z3GpZaTqw',
    appId: '1:241414034513:ios:f08a6c9da0de19bdfd9470',
    messagingSenderId: '241414034513',
    projectId: 'testg2-8640',
    storageBucket: 'testg2-8640.firebasestorage.app',
    iosBundleId: 'com.vibebase.vibebaseApp',
  );

}